### ISSUE TITLE
drive folders support

### ISSUE THREAD

**Issue by costelabr17** [victorrjimenezz/4PT-Repository#2]
Will be a nice move if we can use a gdrive to make our own "pkg store"

**Comment by victorrjimenezz** [comment]
Seems like a good idea for a future update, will look into it :)

**Comment by rmbell** [comment]
Use rclone to mount a gdrive on the web server then point to it. Done.

**Comment by costelabr17** [comment]
> Use rclone to mount a gdrive on the web server then point to it. Done.

Nice tip, i will try, you know any easy way to create .yml file to use on it?

**Comment by victorrjimenezz** [comment]
> 

.yml are plain text files, like txt, you can download the example file and edit it or create one with textedit/notepad and save it as repo.yml. If you mean a GUI that allows you to create the repo.yml file easily, then there is currently no GUI, but it has been noted [here](https://github.com/victorrjimenezz/4PT-Repository/issues/1#issuecomment-1025010021)  and I will begin development shortly

**Comment by victorrjimenezz** [comment]
> > Use rclone to mount a gdrive on the web server then point to it. Done.
> 
> Nice tip, i will try, you know any easy way to create .yml file to use on it?

A GUI has been released to create repositories easily, you can find it here https://github.com/victorrjimenezz/4PT-REPO-GUI/releases/tag/v1.20
